global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: xoxopay-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - xoxopay-backend:3000

  - job_name: xoxopay-contracts
    metrics_path: /metrics/contracts
    static_configs:
      - targets:
          - xoxopay-server:3000
